<?php

/**
 * PluginRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRegion');
    }
}