<?php

/**
 * PluginProvinciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProvinciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProvinciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProvincia');
    }
}