<?php

/**
 * PluginComunaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginComunaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginComunaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginComuna');
    }
}